Matricula/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
urlpatterns = [
    path('', views.home,name='home'),
    path('admin-docente/', views.RegistrarDocente,name='admin-docente'),
    path('lista-docente/', views.ListaDocente,name='lista-docente'),
    path('buscar-docente/', views.BuscarDocente,name='buscar-docente'),
    path('editar-docente/<int:docente_id>/', views.EditarDocente, name='editar-docente'),
    path('editar-docente/<int:docente_id>/guardar/', views.GuardarEditarDocente, name='guardar-editar-docente'),
    path('eliminar-docente/<int:docente_id>/', views.EliminarDocente, name='eliminar-docente'),
    path('admin-alumno/', views.RegistrarAlumno,name='admin-alumno'),
    path('lista-alumno/', views.ListaAlumno,name='lista-alumno'),
    path('buscar-alumno/', views.BuscarAlumno,name='buscar-alumno'),
    path('editar-alumno/<int:alumno_id>/', views.EditarAlumno, name='editar-alumno'),
    path('editar-alumno/<int:alumno_id>/guardar/', views.GuardarEditarAlumno, name='guardar-editar-alumno'),
    path('eliminar-alumno/<int:alumno_id>/', views.EliminarAlumno, name='eliminar-alumno'),
    path('admin-curso/', views.RegistrarCurso,name='admin-curso'),
    path('lista-curso/', views.ListaCurso,name='lista-curso'),
    path('buscar-curso/', views.BuscarCurso,name='buscar-curso'),
    path('editar-curso/<int:curso_id>/', views.EditarCurso, name='editar-curso'),
    path('editar-curso/<int:curso_id>/guardar/', views.GuardarEditarCurso, name='guardar-editar-curso'),
    path('eliminar-curso/<int:curso_id>/', views.EliminarCurso, name='eliminar-curso'),
    path('admin-ciclo/', views.RegistrarCiclo,name='admin-ciclo'),
    path('lista-ciclo/', views.ListaCiclo,name='lista-ciclo'),
    path('buscar-ciclo/', views.BuscarCiclo,name='buscar-ciclo'),
    path('editar-ciclo/<int:ciclo_id>/', views.EditarCiclo, name='editar-ciclo'),
    path('editar-ciclo/<int:ciclo_id>/guardar/', views.GuardarEditarCiclo, name='guardar-editar-ciclo'),
    path('eliminar-ciclo/<int:ciclo_id>/', views.EliminarCiclo, name='eliminar-ciclo'),
    path('admin-gestionar-ciclo/', views.GestionarCiclo,name='admin-gestionar-ciclo'),
    path('lista-gestionar-ciclo/', views.ListaGestionarCiclo,name='lista-gestionar-ciclo'),
    path('buscar-gestionar-ciclo/', views.BuscarGestionarCiclo,name='buscar-gestionar-ciclo'),
    path('editar-gestionar-ciclo/<int:ciclo_id>/', views.EditarGestionarCiclo, name='editar-gestionar-ciclo'),
    path('guardar-editar-gestionar-ciclo/<int:ciclo_id>/', views.GuardarEditarGestionarCiclo, name='guardar-editar-gestionar-ciclo'),
    path('eliminar-gestionar-curso/<int:gestionarcurso_id>/', views.EliminarGestionarCiclo, name='eliminar-gestionar-curso'),
    path('admin-matricula/', views.RegistrarMatricula,name='admin-Matricula'),
    path('buscar-alumno-a-matricular/', views.BuscarAlumnosAMatricular,name='buscar-alumno-a-matricular'),
    path('lista-matricula/', views.ListaMatricula,name='lista-matricula'),
    path('buscar-matricula/', views.BuscarMatricula,name='buscar-matricula'),
    path('editar-matricula/<int:matricula_id>/', views.EditarMatricula, name='editar-matricula'),
    path('guardar-editar-matricula/<int:matricula_id>/', views.GuardarEditarMatricula, name='guardar-editar-matricula'),
    path('eliminar-matricula/<int:matricula_id>/', views.EliminarMatricula, name='eliminar-matricula'),
    path('register/', views.Register, name='register'),
    path('accounts/login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
]

SistemaMatricula/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Matricula.urls')),
]

Matricula/models.py
from django.db import models
from django.core.validators import MinLengthValidator,MaxLengthValidator
from datetime import datetime
# Create your models here.

class Docente(models.Model):
    dni = models.CharField(max_length=8)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    telefono = models.CharField(max_length=13)
    direccion = models.CharField(max_length=300)
    
    def __str__(self):
        data = "{0} {1} {2}"
        return data.format(self.dni,self.nombre, self.apellido)
        

class Alumno(models.Model):
    dni = models.PositiveIntegerField(
    validators=[
        MinLengthValidator(8),  # Mínimo 8 dígitos
        MaxLengthValidator(8)   # Máximo 8 dígitos
    ]
)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    telefono = models.CharField(max_length=13)
    direccion = models.CharField(max_length=300)
    
    def __str__(self):
        data = "{0} {1} {2}"
        return data.format(self.dni,self.nombre, self.apellido)   


class Curso(models.Model):
    nombreCurso = models.CharField(max_length=40)
    vacantes = models.PositiveIntegerField(
    validators=[
        MaxLengthValidator(3)   # Máximo 3 dígitos
    ]
)
    docente = models.ForeignKey(Docente, on_delete=models.PROTECT)
    
    def __str__(self):
        data = "{0} {1} {2}"
        return data.format(self.nombreCurso, self.vacantes, self.docente) 


class Ciclo(models.Model):
    nombreCiclo = models.CharField(max_length=50)
    carrera = models.CharField(max_length=50)
    
    def __str__(self):
        data = "{0} {1} "
        return data.format(self.nombreCiclo, self.carrera) 


class CicloCurso(models.Model):
    ciclo = models.ForeignKey(Ciclo, on_delete=models.PROTECT)
    curso = models.ForeignKey(Curso, on_delete=models.PROTECT)
    def __str__(self):
        data = "{0} {1}"
        return data.format(self.ciclo, self.curso) 

class Matricula(models.Model):
    fecha = models.DateField()  
    alumnoMatricula = models.ForeignKey(Alumno, on_delete=models.PROTECT)
    turno = models.CharField(max_length=15)
    modalidad = models.CharField(max_length=20)
    cicloMatricula = models.ForeignKey(Ciclo, on_delete=models.PROTECT)
    
    def __str__(self):
        return "{0} {1}".format(self.fecha.strftime('%d/%m/%Y'), self.alumnoMatricula) 

Matricula/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirma Contraseña', widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {k: "" for k in fields}

Matricula/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Docente,Alumno,Ciclo,Curso,CicloCurso,Matricula
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from .forms import UserRegisterForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login

def Register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, "Usuario registrado correctamente")
            return redirect('login')
        else:
            errors = form.errors
            password_errors = errors.get('password1', []) + errors.get('password2', [])
            if 'This password is too common.' in password_errors:
                messages.error(request, "Su contraseña no puede ser una clave utilizada comúnmente.")
            else:
                messages.error(request, "Su contraseña debe contener al menos 8 caracteres, (mayúsculas, minúsculas y números)")
                
    else: 
        form = UserRegisterForm()
    context = {'form': form}
    return render(request, 'registration/registro.html', context)

def home(request):
    total_cursos = Curso.objects.all().count()
    total_docentes = Docente.objects.all().count()
    total_alumnos = Alumno.objects.all().count()
    total_matriculados = Matricula.objects.all().count()
    context = {
        'total_cursos': total_cursos,
        'total_docentes': total_docentes,
        'total_alumnos': total_alumnos,
        'total_matriculados': total_matriculados
    }
    return render(request, 'home.html', context)
#Docente

def RegistrarDocente(request):
    dniExiste = False

    if request.method == 'POST':
        dniRegistro = request.POST['dni-registro']
        nombreRegistro = request.POST['nombre-registro']
        apellidoRegistro = request.POST['apellido-registro']
        telefonoRegistro = request.POST['telefono-registro']
        direccionRegistro = request.POST['direccion-registro']

        # Verificar si el Dni ya existe
        dniExiste = Docente.objects.filter(dni__iexact=dniRegistro).exists()

        # Si el Dni ya existe, mostrar SweetAlert and retornar a la misma página
        if dniExiste:
            messages.error(request, "El Docente ya existe")
        # Si el Dni no existe, crear el objeto Docente
        else:
            Docente.objects.create(dni=dniRegistro, nombre=nombreRegistro, apellido=apellidoRegistro, telefono=telefonoRegistro, direccion=direccionRegistro)
            messages.success(request, "Docente Registrado Correctamente")
            return redirect('admin-docente')

    return render(request, 'admin-docente.html', {'dniExiste': dniExiste})
    

def ListaDocente(request):
    listaDocente = Docente.objects.all().order_by('apellido')
    paginator = Paginator(listaDocente, 10)
    pagina = request.GET.get('page') or 1
    listaDocente = paginator.get_page(pagina)
    pagina_actual = int(pagina)
    paginas = range(1, listaDocente.paginator.num_pages + 1)
    context = {
        'listaDocente': listaDocente,
        'paginas': paginas, 
        'pagina_actual': pagina_actual
        }
    return render(request, 'admin-lista-docente.html', context)

def BuscarDocente(request):
    if 'buscar' in request.GET:
        buscarDocente = request.GET['buscar']
        listabusquedaDocente = Docente.objects.filter(
            Q(dni__icontains=buscarDocente) |
            Q(apellido__icontains=buscarDocente)
        ).order_by('apellido')
    else:
        listabusquedaDocente = Docente.objects.all().order_by('apellido')

    paginator = Paginator(listabusquedaDocente, 10)
    pagina = request.GET.get('page') or 1
    listabusquedaDocente = paginator.get_page(pagina)
    pagina_actual = int(pagina)
    paginas = range(1, listabusquedaDocente.paginator.num_pages + 1)

    context = {
        'listabusquedaDocente': listabusquedaDocente,
        'paginas': paginas,
        'pagina_actual': pagina_actual,
    }

    return render(request, 'admin-buscar-docente.html', context)
@login_required
def EditarDocente(request, docente_id):
    docente = get_object_or_404(Docente, pk=docente_id)
    context = {
        'docente': docente,
    }
    return render(request, 'admin-editar-docente.html', context)
@login_required
def GuardarEditarDocente(request, docente_id):
    docente = get_object_or_404(Docente, pk=docente_id)

    if request.method == 'POST':
        dniRegistro = request.POST['dni-registro']
        nombreRegistro = request.POST['nombre-registro']
        apellidoRegistro = request.POST['apellido-registro']
        telefonoRegistro = request.POST['telefono-registro']
        direccionRegistro = request.POST['direccion-registro']

        docente.dni = dniRegistro
        docente.nombre = nombreRegistro
        docente.apellido = apellidoRegistro
        docente.telefono = telefonoRegistro
        docente.direccion = direccionRegistro
        docente.save()

        messages.success(request, "Docente actualizado correctamente.")
        return redirect('lista-docente')

    # Redireccionar a la vista de detalles del docente actualizado
    return redirect('lista-docente', docente_id=docente.id)

@login_required
def EliminarDocente(request,docente_id):
    DocenteEliminar = Docente.objects.get(pk=docente_id)
    DocenteEliminar.delete()
    messages.success(request, "Docente eliminado correctamente.")
    return redirect('/lista-docente')


#Alumno

def RegistrarAlumno(request):
    DniAlumnoExiste = False

    if request.method == 'POST':
        dniRegistro = request.POST['dni-registro']
        nombreRegistro = request.POST['nombre-registro']
        apellidoRegistro = request.POST['apellido-registro']
        telefonoRegistro = request.POST['telefono-registro']
        direccionRegistro = request.POST['direccion-registro']

        # Verificar si el Dni ya existe
        DniAlumnoExiste = Alumno.objects.filter(dni__iexact=dniRegistro).exists()

        # Si el Dni ya existe, mostrar SweetAlert and retornar a la misma página
        if DniAlumnoExiste:
            messages.error(request, "El Estudiante ya existe")
        # Si el Dni no existe, crear el objeto Alumno
        else:
            Alumno.objects.create(dni=dniRegistro, nombre=nombreRegistro, apellido=apellidoRegistro, telefono=telefonoRegistro, direccion=direccionRegistro)
            messages.success(request, "Estudiante Registrado Correctamente")
            return redirect('admin-alumno')
    context ={
            'DniAlumnoExiste': DniAlumnoExiste,
            }
    return render(request, 'admin-alumno.html', context) 

def ListaAlumno(request):
    listaAlumno = Alumno.objects.all().order_by('apellido')
    paginator = Paginator(listaAlumno, 10)
    pagina = request.GET.get('page') or 1
    listaAlumno = paginator.get_page(pagina)
    pagina_actual = int(pagina)
    paginas = range(1, listaAlumno.paginator.num_pages + 1)
    context = {
        'listaAlumno': listaAlumno,
        'paginas': paginas, 
        'pagina_actual': pagina_actual
        }
    
    return render(request, 'admin-lista-alumno.html', context)

def BuscarAlumno(request):
    if 'buscar' in request.GET:
        buscarAlumno = request.GET['buscar']
        listabusquedaAlumno = Alumno.objects.filter(
            Q(dni__icontains=buscarAlumno) |
            Q(apellido__icontains=buscarAlumno)
        ).order_by('apellido')
    else:
        listabusquedaAlumno = Alumno.objects.all().order_by('apellido')

    paginator = Paginator(listabusquedaAlumno, 10)
    pagina = request.GET.get('page') or 1
    listabusquedaAlumno = paginator.get_page(pagina)
    pagina_actual = int(pagina)
    paginas = range(1, listabusquedaAlumno.paginator.num_pages + 1)

    context = {
        'listabusquedaAlumno': listabusquedaAlumno,
        'paginas': paginas,
        'pagina_actual': pagina_actual,
    }
    
    return render(request, 'admin-buscar-alumno.html', context)
@login_required
def EditarAlumno(request, alumno_id):
    alumno = get_object_or_404(Alumno, pk=alumno_id)
    context = {
        'alumno': alumno,
    }
    return render(request, 'admin-editar-alumno.html', context)
@login_required
def GuardarEditarAlumno(request, alumno_id):
    alumno = get_object_or_404(Alumno, pk=alumno_id)

    if request.method == 'POST':
        dniRegistro = request.POST['dni-registro']
        nombreRegistro = request.POST['nombre-registro']
        apellidoRegistro = request.POST['apellido-registro']
        telefonoRegistro = request.POST['telefono-registro']
        direccionRegistro = request.POST['direccion-registro']

        alumno.dni = dniRegistro
        alumno.nombre = nombreRegistro
        alumno.apellido = apellidoRegistro
        alumno.telefono = telefonoRegistro
        alumno.direccion = direccionRegistro
        alumno.save()

        messages.success(request, "Alumno actualizado correctamente.")
        return redirect('lista-alumno')

    # Redireccionar a la vista de detalles del alumno actualizado
    return redirect('lista-alumno', alumno_id=alumno.id)
@login_required
def EliminarAlumno(request,alumno_id):
    AlumnoEliminar = Alumno.objects.get(pk=alumno_id)
    AlumnoEliminar.delete()
    messages.success(request, "Estudiante eliminado correctamente.")
    return redirect('/lista-alumno')

#Curso

def RegistrarCurso(request):
    docentes = Docente.objects.all()  # Obtener todos los docentes de la base de datos

    if request.method == 'POST':
        # Obtener los datos del formulario enviado por el usuario
        nombre_curso = request.POST.get('nombrecurso-reg')
        vacantes_str = request.POST.get('vacantes-reg')
        docente_id = request.POST.get('direccion-reg')

        # Validar que se haya seleccionado un docente
        if not docente_id:

Matricula/templates/admin-buscar-matricula.html
{% extends "./base.html" %}
{% block title %} Buscar Matrícula {% endblock %}

{% block section %}

<div class="container-fluid">
    <div class="page-header">
    <h1 class="text-titles"><i class="zmdi zmdi-account zmdi-hc-fw"></i> ADMIN <small>MATRÍCULA</small></h1>
    </div>
    <p class="lead">Panel de Administración para buscar Matrículas registradas, utiliza criterios como apellido o DNI, puedes realizar búsquedas precisas y obtener resultados relevantes. </p>
</div>

<div class="container-fluid">
    <ul class="breadcrumb breadcrumb-tabs">
        <li>
            <a href="{{ '/admin-matricula/' }}" class="btn btn-info">
                <i class="zmdi zmdi-plus"></i> &nbsp; NUEVA MATRÍCULA
            </a>
        </li>
        <li>
            <a href="{{ '/lista-matricula/' }}" class="btn btn-success">
                <i class="zmdi zmdi-format-list-bulleted"></i> &nbsp; LISTA DE MATRÍCULA
            </a>
        </li>
        <li>
            <a href="{{ '/buscar-matricula/' }}" class="btn btn-primary">
                <i class="zmdi zmdi-search"></i> &nbsp; BUSCAR MATRÍCULA
            </a>
        </li>
    </ul>
</div>

<div class="container-fluid">
    <form action="{% url 'buscar-matricula' %}" class="well" method="get">
        {% csrf_token %}
        <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
                <div class="form-group label-floating">
                    <span class="control-label">¿A quién estás buscando? Ingrese DNI o Apellido</span>
                    <input class="form-control" type="text" name="buscar" value="{{ buscarAlumno }}">
                </div>
            </div>
            <div class="col-xs-12">
                <p class="text-center">
                    <button type="submit" class="btn btn-primary btn-raised btn-sm"><i class="zmdi zmdi-search"></i> &nbsp; Buscar</button>
                </p>
            </div>
        </div>
    </form>
</div>


<!---->

<div class="container-fluid">
    <div class="panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="zmdi zmdi-format-list-bulleted"></i> &nbsp; LISTA DE MATRÍCULA</h3>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-hover text-center">
                    <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th class="text-center">FECHA</th>
                            <th class="text-center">ALUMNO</th>
                            <th class="text-center">TURNO</th>
                            <th class="text-center">MODALIDAD</th>
                            <th class="text-center">CICLO</th>
                            <th class="text-center">CURSOS</th>
                            <th class="text-center">EDITAR</th>
                            <th class="text-center">ELIMINAR</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for matricula in listaMatricula %}
                            <tr>
                                <td>{{ listaMatricula.start_index|add:forloop.counter0 }}</td>
                                <td>{{ matricula.fecha }}</td>
                                <td>{{ matricula.alumnoMatricula.nombre }} {{ matricula.alumnoMatricula.apellido }}</td>
                                <td>{{ matricula.turno }}</td>
                                <td>{{ matricula.modalidad }}</td>
                                <td>{{ matricula.cicloMatricula.nombreCiclo }}</td>
                                <td>
                                    <ul>
                                        {% for ciclo_curso in matricula.cicloMatricula.ciclocurso_set.all %}
                                        <li>{{ ciclo_curso.curso.nombreCurso }}</li>
                                        {% endfor %}
                                    </ul>
                                </td>
                                <td>
                                    <a href="{% url 'editar-matricula' matricula.id %}" class="btn btn-success btn-raised btn-xs">
                                        <i class="zmdi zmdi-refresh"></i> 
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'eliminar-matricula' matricula.id %}" class="btn btn-danger btn-raised btn-xs">
                                        <i class="zmdi zmdi-delete"></i> 
                                    </a>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="9">No se encontraron resultados.</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="9">{% include "paginacion-buscar-matricula.html" %}</td>
                        </tr>
                    </tfoot>
                </table>

            </div>
            
        </div>
    </div>
</div>
{% endblock %}

Matricula/templates/admin-ciclo.html
{% extends "./base.html" %}
{% block title %} Ciclos {% endblock %}

{% block section %}

<div class="container-fluid">
    <div class="page-header">
    <h1 class="text-titles"><i class="zmdi zmdi-account zmdi-hc-fw"></i> ADMIN <small>CICLO</small></h1>
    </div>
    <p class="lead">Panel de Administración dedicado a la gestión de ciclos académicos, podrás agregar fácilmente nuevos ciclos al sistema. Registra la información relevante de cada ciclo de manera rápida y sencilla. </p>
</div>

<div class="container-fluid">
    <ul class="breadcrumb breadcrumb-tabs">
        <li>
            <a href="{{ '/admin-ciclo/' }}" class="btn btn-info">
                <i class="zmdi zmdi-plus"></i> &nbsp; NUEVO CICLO
            </a>
        </li>
        <li>
            <a href="{{ '/lista-ciclo/' }}" class="btn btn-success">
                <i class="zmdi zmdi-format-list-bulleted"></i> &nbsp; LISTA DE CICLO
            </a>
        </li>
        <li>
            <a href="{{ '/buscar-ciclo/' }}" class="btn btn-primary">
                <i class="zmdi zmdi-search"></i> &nbsp; BUSCAR CICLO
            </a>
        </li>
    </ul>
</div>


<div class="container-fluid">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="zmdi zmdi-plus"></i> &nbsp; NUEVO CICLO</h3>
        </div>
        <div class="panel-body">
            <form method="post" action="{% url 'admin-ciclo' %}">
                {% csrf_token %}
                <fieldset>
                    <legend><i class="zmdi zmdi-account-box"></i> &nbsp; Información de Ciclo</legend>
                    <div class="container-fluid">
                        <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group label-floating">
                                    <label class="control-label">Número de Ciclo *</label>
                                    <input pattern="[0-9-]{1,10}" class="form-control" type="text" name="numerociclo-reg" required="" maxlength="10">
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-8">
                            <div class="form-group label-floating">
                                <label class="control-label">Carrera</label>
                                <select name="direccion-reg" class="form-control">
                                    <option value="opcion1">- Seleccionar -</option>
                                    <option value="Computación e Informática">Computación e Informática</option>
                                    <option value="Administración de Empresas">Administración de Empresas</option>
                                    <option value="Marketing Digital">Marketing Digital</option>
                                    
                                </select>
                            </div>
                        </div>
                        
                        
                        </div>
                    </div>
                </fieldset>
                <br>
                
                <p class="text-center" style="margin-top: 20px;">
                    <button type="submit" class="btn btn-info btn-raised btn-sm"><i class="zmdi zmdi-floppy"></i> Guardar</button>
                </p>
            </form>
        </div>
    </div>
</div>

{% endblock %}

Matricula/templates/admin-curso.html
{% extends "./base.html" %}
{% block title %} Cursos {% endblock %}

{% block section %}

<div class="container-fluid">
    <div class="page-header">
    <h1 class="text-titles"><i class="zmdi zmdi-account zmdi-hc-fw"></i> ADMIN <small>CURSO</small></h1>
    </div>
    <p class="lead">Panel de Administración dedicado a la gestión de cursos, podrás agregar fácilmente nuevos curos al sistema. Registra la información relevante de cada curso de manera rápida y sencilla. </p>
</div>

<div class="container-fluid">
    <ul class="breadcrumb breadcrumb-tabs">
        <li>
            <a href="{{ '/admin-curso/' }}" class="btn btn-info">
                <i class="zmdi zmdi-plus"></i> &nbsp; NUEVO CURSO
            </a>
        </li>
        <li>
            <a href="{{ '/lista-curso/' }}" class="btn btn-success">
                <i class="zmdi zmdi-format-list-bulleted"></i> &nbsp; LISTA DE CURSO
            </a>
        </li>
        <li>
            <a href="{{ '/buscar-curso/' }}" class="btn btn-primary">
                <i class="zmdi zmdi-search"></i> &nbsp; BUSCAR CURSO
            </a>
        </li>
    </ul>
</div>


<div class="container-fluid">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="zmdi zmdi-plus"></i> &nbsp; NUEVO CURSO</h3>
        </div>
        <div class="panel-body">
            <form action="/admin-curso/" method="POST">{% csrf_token %}
                <fieldset>
                    <legend><i class="zmdi zmdi-account-box"></i> &nbsp; Información de Curso</legend>
                    <div class="container-fluid">
                        <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group label-floating">
                                    <label class="control-label">Nombre de Curso*</label>
                                    <input pattern="[a-zA-ZáéíóúÁÉÍÓÚñÑ ]{1,40}" class="form-control" type="text" name="nombrecurso-reg" required="" maxlength="40">
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-8">
                            <div class="form-group label-floating">
                                    <label class="control-label">Vacantes *</label>
                                    <input pattern="[0-9]{1,5}" class="form-control" type="text" name="vacantes-reg" required="" maxlength="5">
                            </div>
                        </div>
                        
                        <div class="col-xs-12 col-sm-8">
                            <div class="form-group label-floating">
                                <label class="control-label">Docente</label>
                                <select name="direccion-reg" class="form-control">
                                    <option value="">- Seleccionar -</option>
                                    {% for docente in docentes %}
                                        <option value="{{ docente.id }}">{{ docente.nombre }} {{ docente.apellido }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        </div>
                    </div>
                </fieldset>
                <br>
                
                <p class="text-center" style="margin-top: 20px;">
                    <button type="submit" class="btn btn-info btn-raised btn-sm"><i class="zmdi zmdi-floppy"></i> Guardar</button>
                </p>
            </form>
        </div>
    </div>
</div>

{% endblock %}